### ISSUE TITLE
naming of flim_add

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/analysis#29]
https://github.com/math-comp/analysis/blob/aa351f34edbf0c45fc88cd5528749803bf1e8b3f/hierarchy.v#L1490

Is that a good name? With that name, I was rather expecting a lemma such as
Lemma lim_add (F : filter_on X) (f g : X -> Y) (a b : Y) :
  f @ F --> a -> g @ F --> b -> (f + g) @ F --> a + b.
(no prod, following flim_const).

**Comment by CohenCyril** [comment]
You are right, this should be rather be called `add_continuous`.
Note that in prinicple, `lim_add` is a corollary.

**Comment by strub** [comment]
Why not `limD`. This is the name I gave to this lemma in my branch.

**Comment by affeldt-aist** [comment]
Indeed, limD looks like a more appropriate naming scheme.

**Comment by drouhling** [comment]
Since we are talking about renaming, let's generalize this issue to the whole repository.

I believe that compatibility with Coquelicot is not a concern any more, so we should discuss about what we want to keep and what we want to change.
There are some remnants of Coquelicot that pollute the code:
- commented lemmas that are not ported yet; do we want to port them?
- admitted (non ported) lemmas; which ones do we use and want to keep?
- constructions that seem to have no use, e.g. `locally_dist`.
  https://github.com/math-comp/analysis/blob/abb66fa649a4c6ee061a211c4c834242418d325c/hierarchy.v#L649-L654
- names, since we are talking about changing the naming convention.

**Comment by CohenCyril** [comment]
Let us use:
- `approaches` prefix for `F --> x`,
- `lim` for `lim F` and
- `continuous` for continuity
